# Generated by Django 3.2.6 on 2021-08-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("trace_id", models.AutoField(primary_key=True, serialize=False)),
                ("addr", models.CharField(max_length=30)),
                ("floor_num", models.CharField(max_length=15)),
                ("room_num", models.CharField(max_length=15)),
                ("komm_name", models.CharField(max_length=25)),
                ("port_num", models.CharField(max_length=15)),
                ("patch_panel", models.CharField(max_length=25)),
                ("roz_name", models.CharField(max_length=18)),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "cur_journal",
            },
        ),
    ]
