# Generated by Django 3.2.6 on 2021-08-12 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="item",
            table=None,
        ),
    ]
