# Generated by Django 3.2.6 on 2021-08-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_alter_item_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="addr",
            field=models.CharField(
                max_length=30, verbose_name="Адрес расположения трассы"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="floor_num",
            field=models.CharField(max_length=15, verbose_name="Номер этажа"),
        ),
        migrations.AlterField(
            model_name="item",
            name="komm_name",
            field=models.CharField(
                max_length=25, verbose_name="Наименование коммутатора"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="notes",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Прочие примечания и отметки",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="patch_panel",
            field=models.CharField(
                max_length=25, verbose_name="Обозначение идентификатора патч-панели"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="port_num",
            field=models.CharField(
                max_length=15, verbose_name="Номер порта коммутатора"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="room_num",
            field=models.CharField(max_length=15, verbose_name="Номер комнаты"),
        ),
        migrations.AlterField(
            model_name="item",
            name="roz_name",
            field=models.CharField(
                max_length=18, verbose_name="Номер или наименование розетки в комнате"
            ),
        ),
    ]
